name: workflow_first

on:
  push:
    branches: [ branch1 ]
  pull_request: 
    branches: [ main ]
    
  workflow_dispatch: 

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List of files in current directory
        run: ls -la

      - name: Output of file contents
        run: |
          echo Hello
          cat file.txt
